export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
